### ISSUE TITLE
AttributeError: 'ANetAstrometryTask' object has no attribute 'distortionContext

### ISSUE THREAD

**Issue by LydiaMak** [GOTO-OBS/obs_goto#2]
```Traceback (most recent call last):
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_base/15.0-6-gfa9b38f+3/python/lsst/pipe/base/cmdLineTask.py", line 392, in __call__
    result = task.run(dataRef, **kwargs)
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_drivers/15.0-5-gf788cd9+4/python/lsst/pipe/drivers/singleFrameDriver.py", line 72, in run
    return self.processCcd.run(sensorRef)
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_base/15.0-6-gfa9b38f+3/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_tasks/15.0-13-g5992896b+2/python/lsst/pipe/tasks/processCcd.py", line 188, in run
    doUnpersist=False,
  File "/local/lydia/lsstsw_v15/stack/Linux64/obs_goto/real/python/lsst/obs/goto/gotoCharTask.py", line 42, in run
    exposure=exposure,
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_base/15.0-6-gfa9b38f+3/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/local/lydia/lsstsw_v15/stack/Linux64/obs_goto/real/python/lsst/obs/goto/astrometry.py", line 116, in run
    sourceCat=sourceCat)
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_base/15.0-6-gfa9b38f+3/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/local/lydia/lsstsw_v15/stack/Linux64/meas_extensions_astrometryNet/15.0-4-g6cecc1a/python/lsst/meas/extensions/astrometryNet/anetAstrometry.py", line 197, in run
    return self.solve(exposure=exposure, sourceCat=sourceCat)
  File "/local/lydia/lsstsw_v15/stack/Linux64/pipe_base/15.0-6-gfa9b38f+3/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/local/lydia/lsstsw_v15/stack/Linux64/meas_extensions_astrometryNet/15.0-4-g6cecc1a/python/lsst/meas/extensions/astrometryNet/anetAstrometry.py", line 227, in solve
    with self.distortionContext(sourceCat=sourceCat, exposure=exposure) as bbox:
```

**Comment by LydiaMak** [comment]
@jrmullaney In /local/ph1jxm/lsstsw/stack/Linux64/meas_extensions_astrometryNet/15.0-1-gc45031d+12/python/lsst/meas/extensions/astrometryNet/anetAstrometry.py

the lines:
with self.distortionContext(sourceCat=sourceCat, exposure=exposure) as bbox:
           results = self._astrometry(sourceCat=sourceCat, exposure=exposure, bbox=bbox)

are commented out. Did you comment them out or it was a previous version and there's a bug in the code now?
